Services/TodoPlan/TodoPlan.WebUI/Models/ErrorViewModel.cs
namespace TodoPlan.WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Services/TodoPlan/TodoPlan.WebUI/Controllers/DeveloperController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TodoPlan.Core.Dtos;
using TodoPlan.Core.Models;
using TodoPlan.Core.Repositories;
using TodoPlan.Repo;

namespace TodoPlan.WebUI.Controllers
{
    public class DeveloperController : Controller
    {
        private readonly IGenericRepository<Developer> _devRepo;
        private readonly IGenericRepository<Todo> _todoRepo;

        private readonly TodoPlanContext _context;

        public DeveloperController(IGenericRepository<Developer> devRepo, IGenericRepository<Todo> todoRepo, TodoPlanContext context)
        {
            _devRepo = devRepo;
            _todoRepo = todoRepo;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var developers = await _devRepo.GetAll().ToListAsync();
            return View(developers);
        }

        public IActionResult Details(int developerId)
        {
            var dev = _context.Developers
                .Include(x => x.DeveloperTodos)
                .ThenInclude(x => x.Todo)
                .FirstOrDefault(x => x.Id == developerId);
            return View(dev);
        }

    }
}

Services/TodoPlan/TodoPlan.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TodoPlan.WebUI.Models;

namespace TodoPlan.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Services/TodoPlan/TodoPlan.WebUI/Controllers/TodoPlanController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TodoPlan.Core.Models;
using TodoPlan.Repo;

namespace TodoPlan.WebUI.Controllers
{
    public class TodoPlanController : Controller
    {
        private readonly TodoPlanContext _context;

        public TodoPlanController(TodoPlanContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var developers = _context.Developers.ToList();
            var todos = _context.Todos.ToList();

            ViewBag.Developers = developers;
            ViewBag.Todos = todos;

            return View();
        }

        public async Task<IActionResult> TaskAssign()
        {
            var developers = _context.Developers.ToList();
            var todos = _context.Todos.Where(x => x.IsAssigned == false).ToList();

            while (todos.Count > 0)
            {
                todos = _context.Todos.Where(x => x.IsAssigned == false).ToList();
                foreach (var todo in todos)
                {
                    foreach (var developer in developers)
                    {
                        if (developer.Difficulty == todo.Zorluk)
                        {
                            if (developer.WeeklyWorkingHours > 0 && ((developer.WeeklyWorkingHours - todo.Sure) > 0))
                            {
                                developer.WeeklyWorkingHours -= todo.Sure;
                                todo.IsAssigned = true;

                                var devTodo = new DeveloperTodo()
                                {
                                    DeveloperId = developer.Id,
                                    TodoId = todo.Id
                                };

                                await _context.AddAsync(devTodo);
                                await _context.SaveChangesAsync();

                            }
                        }
                    }
                }

                await _context.Developers.ForEachAsync(x => x.WeeklyWorkingHours = 45);
                await _context.SaveChangesAsync();
            }


            return RedirectToAction("Index");
        }
    }
}

Services/TodoPlan/TodoPlan.WebUI/Views/Developer/AddTaskDeveloper.cshtml
@model TodoPlan.Core.Dtos.DeveloperTodoCreateDto

@{
    Layout = "_Layout";
}

<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <form asp-action="AddTaskDeveloper" method="post">
                    <div class="input-group">
                        <input type="hidden" asp-for="DeveloperId" value="@ViewBag.DeveloperId"/>
                        <input type="text" value="@ViewBag.DeveloperName" disabled="disabled"/>
                    </div>
                    <hr/>
                    <div class="input-group">
                        <select asp-for="TodoId">
                            @foreach (var item in ViewBag.Todos)
                            {
                                <option value="@item.Id">@item.Id</option>
                            }
                        </select>
                    </div>
                    <hr/>
                    <button type="submit">Atama Yap</button>
                </form>
            </div>
        </div>

        
    </div>
</div>

Services/TodoPlan/TodoPlan.WebUI/Views/Developer/Details.cshtml
@model TodoPlan.Core.Models.Developer

@{
    Layout = "_Layout";
}

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <div class="card-title">
                    Developer Bilgisi
                </div>
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Dev Name</th>
                            <th>WeeklyWorkingHours</th>
                            <th>Duration</th>
                            <th>Difficulty</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Model.Name</td>
                            <td>@Model.WeeklyWorkingHours</td>
                            <td>@Model.Duration</td>
                            <td>@Model.Difficulty</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <div class="card-title">
                    Atanan İşler
                </div>
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Task ID</th>
                            <th>Süre</th>
                            <th>Zorluk</th>
                            <th>IsAssigned</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var todo in Model.DeveloperTodos)
                        {
                            <tr>
                                <td>@todo.Todo.Id</td>
                                <td>@todo.Todo.Sure</td>
                                <td>@todo.Todo.Zorluk</td>
                                <td>@todo.Todo.IsAssigned</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Services/TodoPlan/TodoPlan.WebUI/Views/Developer/Index.cshtml
@model List<TodoPlan.Core.Models.Developer>

@{
    Layout = "_Layout";
}


<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Weekly Working Hours</th>
                        <th>Duration</th>
                        <th>Difficulty</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.WeeklyWorkingHours</td>
                            <td>@item.Duration</td>
                            <td>@item.Difficulty</td>
                            <td>
                                <a asp-controller="Developer" asp-action="AddTaskDeveloper" asp-route-developerId="@item.Id">Atama Yap</a>
                                <a asp-controller="Developer" asp-action="AddTaskDeveloper" asp-route-developerId="@item.Id">Atama Yap</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Services/TodoPlan/TodoPlan.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Services/TodoPlan/TodoPlan.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TodoPlan.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TodoPlan.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TodoPlan.WebUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TodoPlan" asp-action="Index">Todo Plan</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TodoPlan.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Services/TodoPlan/TodoPlan.WebUI/Views/TodoPlan/Index.cshtml
@{
    Layout = "_Layout";
}

<div class="row mb-2">
    <div class="col-md-12">
        @{
            var todoss = ViewBag.Todos;
            if (todoss.Count > 0)
            {
                <a class="btn btn-success" asp-action="TaskAssign">Otomatik Atama Yap</a>
            }
        }
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Dev Name</th>
                                <th>WeeklyWorkingHours</th>
                                <th>Duration</th>
                                <th>Difficulty</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var dev in ViewBag.Developers)
                            {
                                <tr>
                                    <td>@dev.Name</td>
                                    <td>@dev.WeeklyWorkingHours</td>
                                    <td>@dev.Duration</td>
                                    <td>@dev.Difficulty</td>
                                    <td>
                                        <a asp-controller="Developer" asp-action="Details" asp-route-developerId="@dev.Id" class="btn btn-link">Atanan İşleri</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Task ID</th>
                                <th>Süre</th>
                                <th>Zorluk</th>
                                <th>IsAssigned</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var dev in ViewBag.Todos)
                            {
                                <tr>
                                    <td>@dev.Id</td>
                                    <td>@dev.Sure</td>
                                    <td>@dev.Zorluk</td>
                                    <td>@dev.IsAssigned</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>